//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obsGrup5
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcilanDersler
    {
        public int ADId { get; set; }
        public string DersKodu { get; set; }
        public string DersAdi { get; set; }
        public Nullable<int> AkademisyenId { get; set; }
        public string YariYil { get; set; }
        public Nullable<int> YilDers { get; set; }
    }
}
