//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obsGrup5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bolum
    {
        public Bolum()
        {
            this.DersSorumlulari = new HashSet<DersSorumlulari>();
        }
    
        public string Id { get; set; }
        public string BolumAdi { get; set; }
        public string BolumKodu { get; set; }
        public string Telefon { get; set; }
        public string Fax { get; set; }
        public Nullable<int> Fakulte_id { get; set; }
    
        public virtual Fakulte Fakulte { get; set; }
        public virtual ICollection<DersSorumlulari> DersSorumlulari { get; set; }
    }
}
