//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obsGrup5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donemler
    {
        public Donemler()
        {
            this.Dersler = new HashSet<Dersler>();
        }
    
        public string Donem { get; set; }
        public Nullable<int> Kredi_sayisi { get; set; }
        public Nullable<int> Secmeli_kredi { get; set; }
        public Nullable<int> Zorunlu_kredi { get; set; }
        public Nullable<int> Toplam_ders { get; set; }
        public Nullable<int> Toplam_secmeli_sayisi { get; set; }
    
        public virtual ICollection<Dersler> Dersler { get; set; }
    }
}
