//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obsGrup5
{
    using System;
    using System.Collections.Generic;
    
    public partial class EgitimPlani
    {
        public int Id { get; set; }
        public string BolumAdi { get; set; }
        public string Onay_tarihi { get; set; }
        public string Donem { get; set; }
        public string BolumKodu { get; set; }
    }
}
