//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obsGrup5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Idari
    {
        public int Id { get; set; }
        public string Unvan { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string Mail { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Adres { get; set; }
        public string BolumKodu { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
    }
}
