//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obsGrup5
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ObsMssqlEntities : DbContext
    {
        public ObsMssqlEntities()
            : base("name=ObsMssqlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcilanDersler> AcilanDersler { get; set; }
        public virtual DbSet<Bolum> Bolum { get; set; }
        public virtual DbSet<Dersler> Dersler { get; set; }
        public virtual DbSet<DersSorumlulari> DersSorumlulari { get; set; }
        public virtual DbSet<Donemler> Donemler { get; set; }
        public virtual DbSet<EgitimPlani> EgitimPlani { get; set; }
        public virtual DbSet<Fakulte> Fakulte { get; set; }
        public virtual DbSet<Idari> Idari { get; set; }
        public virtual DbSet<Kayit> Kayit { get; set; }
        public virtual DbSet<Notlar> Notlar { get; set; }
        public virtual DbSet<Ogrenci> Ogrenci { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
