//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obsGrup5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notlar
    {
        public int NotId { get; set; }
        public Nullable<int> KayitId { get; set; }
        public Nullable<int> Vize { get; set; }
        public Nullable<int> Final { get; set; }
        public Nullable<int> But { get; set; }
        public Nullable<double> YilNot { get; set; }
        public string HarfNotu { get; set; }
        public string OtomatikMi { get; set; }
    }
}
