//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obsGrup5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenci
    {
        public int OgrenciNo { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Cinsiyet { get; set; }
        public string DogumTarihi { get; set; }
        public string Eposta { get; set; }
        public string Telefon { get; set; }
        public Nullable<double> MezunOlunanOkulPuani { get; set; }
        public string AktifKayitDonemi { get; set; }
        public Nullable<int> DanismanId { get; set; }
        public Nullable<int> OnayDurum { get; set; }
    }
}
